export const config={runtime:'edge'};
const sources=[{name:'العربية',domain:'alarabiya.net'},{name:'الشرق للأخبار',domain:'asharq.com'},{name:'سكاي نيوز عربية',domain:'skynewsarabia.com'},{name:'CNN بالعربية',domain:'arabic.cnn.com'},{name:'الجزيرة',domain:'aljazeera.net'}];
const A='https://www.alarabiya.net';
function dec(s=''){let x=s.replace(/<!\[CDATA\[|\]\]>/g,'');for(let i=0;i<3;i++)x=x.replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&nbsp;|&#160;|&#xA0;/gi,' ');return x}
function txt(s=''){return dec(s).replace(/<[^>]+>/g,' ').replace(/&[a-zA-Z0-9#]+;/g,' ').replace(/\s+/g,' ').trim()}
function tag(b,n){const m=b.match(new RegExp('<'+n+'(?:\\s[^>]*)?>([\\s\\S]*?)<\\/'+n+'>','i'));return m?dec(m[1].trim()):''}
function parse(xml,source){return[...xml.matchAll(/<item(?:\s[^>]*)?>([\s\S]*?)<\/item>/gi)].slice(0,15).map(x=>x[1]).map(b=>({title:txt(tag(b,'title')).replace(/\s+-\s+[^-]+$/,'').trim(),url:tag(b,'link'),source,date:tag(b,'pubDate')})).filter(x=>x.title)}
function meta(h,key){const tags=h.match(/<meta\b[^>]*>/gi)||[];for(const t of tags){const k=(t.match(/(?:property|name)=["']([^"']+)["']/i)||[])[1];if(k!==key)continue;const v=(t.match(/content=["']([^"']*)["']/i)||[])[1];if(v)return txt(v)}return''}
function objects(v,out=[]){if(!v||typeof v!=='object')return out;if(Array.isArray(v)){v.forEach(x=>objects(x,out));return out}out.push(v);Object.values(v).forEach(x=>objects(x,out));return out}
function articleData(h){for(const m of h.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{for(const o of objects(JSON.parse(m[1]))){if(o&&(o.headline||o.name)&&(o.articleBody||o.description)){const title=txt(o.headline||o.name),body=txt(o.articleBody||o.description),url=typeof o.url==='string'?o.url:(o.mainEntityOfPage&&o.mainEntityOfPage['@id'])||'';if(title&&body.split(/\s+/).length>=30)return{title,body,url,date:o.datePublished||''}}}}catch{}}return null}
async function directArabia(){const feeds=[A+'/tools/mrss',A+'/tools/rss',A+'/rss.xml'];const links=[];for(const u of feeds){try{const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/rss+xml,application/xml,text/xml,text/html'},redirect:'follow',cache:'no-store'});if(!r.ok)continue;const h=await r.text();for(const m of h.matchAll(/https?:\\?\/\\?\/[^"'<>\\s]+/gi)){let x=m[0].replace(/\\\//g,'/').replace(/&amp;/g,'&');if(x.includes('alarabiya.net')&&!x.includes('/tools/')&&!links.includes(x))links.push(x)}}catch{}}if(!links.length){for(const page of [A,A+'/saudi-today',A+'/arab-and-world']){try{const r=await fetch(page,{headers:{'User-Agent':'Mozilla/5.0'},cache:'no-store'});if(!r.ok)continue;const h=await r.text();for(const m of h.matchAll(/href=["']([^"']+)["']/gi)){let x=m[1];if(x.startsWith('/'))x=A+x;if(x.startsWith(A)&&!x.includes('/tools/')&&!links.includes(x))links.push(x)}}catch{}}}const found=[];for(const u of links.slice(0,30)){try{const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0'},redirect:'follow',cache:'no-store'});if(!r.ok)continue;const h=await r.text(),j=articleData(h);let title=j?.title||meta(h,'og:title'),body=j?.body||meta(h,'og:description')||meta(h,'description');let words=txt(body).split(/\s+/).filter(Boolean);if(title&&words.length>=30){if(words.length>90)words=words.slice(0,90);found.push({title:txt(title),description:words.join(' ')+(txt(body).split(/\s+/).length>90?'…':''),url:u,source:'العربية',date:j?.date||''})}if(found.length>=8)break}catch{}}return{found,linkCount:links.length}}
export default async function handler(){const [direct,settled]=await Promise.all([directArabia(),Promise.allSettled(sources.map(async s=>{const q=encodeURIComponent('site:'+s.domain),url='https://news.google.com/rss/search?q='+q+'&hl=ar&gl=SA&ceid=SA:ar';const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0'},cache:'no-store'});if(!r.ok)throw 0;return parse(await r.text(),s.name)}))]);const hero=direct.found;const items=settled.flatMap(x=>x.status==='fulfilled'?x.value:[]);return new Response(JSON.stringify({hero,items,diagnostic:{directArabiaCount:hero.length,directArabiaOk:hero.length>0,directLinkCount:direct.linkCount,generatedAt:new Date().toISOString()}}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, s-maxage=180'}})}